// Code generated by mockery v2.48.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/kberestov/metrics-tpl/internal/common/domain"
	mock "github.com/stretchr/testify/mock"
)

// MetricUpdater is an autogenerated mock type for the MetricUpdater type
type MetricUpdater struct {
	mock.Mock
}

// Update provides a mock function with given fields: n, v
func (_m *MetricUpdater) Update(n domain.MetricName, v domain.MetricValue) error {
	ret := _m.Called(n, v)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.MetricName, domain.MetricValue) error); ok {
		r0 = rf(n, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMetricUpdater creates a new instance of MetricUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricUpdater {
	mock := &MetricUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
